export const actions = {
    FETCH_LIST: 'FETCH_LIST',
    FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
    FETCH_LIST_ERROR: 'FETCH_LIST_ERROR',
    FETCH_ITEM: 'FETCH_ITEM',
    CLOSE_ITEM: 'CLOSE_ITEM',
    FETCH_ITEM_SUCCESS: 'FETCH_ITEM_SUCCESS',
    FETCH_ITEM_ERROR: 'FETCH_ITEM_ERROR',
}



